name: 12-hours-cron
on:
  schedule:
    - cron: "* */12 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Check new articles
        env:
          API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
        run: |
          curl --request POST \
          --url 'https://omocoro-archive.kk-web.link/api/articles' \
          --header 'Authorization: Bearer $API_SECRET_KEY'
